/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mp3p1.Archivo;
import mp3p1.Cancion;
import mp3p1.Temporal;

/**
 *
 * @author Diego
 */
public class Letra extends javax.swing.JFrame {

    /**
     * Creates new form Letra
     */
    Temporal tem=new Temporal();
    public Letra() throws IOException {
        initComponents();
        tieneLetra();
        
        
      
    }
    String convertByteToString(byte byteValue) 
    { 
  
        // Convert byte value to String value 
        // using + operator method 
        String stringValue = "" + byteValue; 
  
        return (stringValue); 
    } 
    
    public void tieneLetra() throws FileNotFoundException, IOException{
        if (tem.getSong().getLetra().equals("N")) {
            this.txaLetra.setText("esta cancion no cuenta con letra puede ingresar una seleccionando modificar");
        }else{
            String ruta=tem.getSong().getLetra();
            RandomAccessFile archivo = new RandomAccessFile(ruta, "rw");
            String texto=archivo.readUTF();
            this.txaLetra.setText(texto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaLetra = new javax.swing.JTextArea();
        rModificar = new javax.swing.JRadioButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txaLetra.setColumns(20);
        txaLetra.setRows(5);
        txaLetra.setEnabled(false);
        jScrollPane1.setViewportView(txaLetra);

        rModificar.setText("Modificar");
        rModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rModificarMouseClicked(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.setEnabled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(rModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmar)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rModificar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rModificarMouseClicked
        // TODO add your handling code here:
        if (rModificar.isSelected()) {
           this.btnConfirmar.setEnabled(true);
           this.txaLetra.setEnabled(true);
        } else {
           this.btnConfirmar.setEnabled(false);
           this.txaLetra.setEnabled(false);
        }
    }//GEN-LAST:event_rModificarMouseClicked

    
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
          int n = JOptionPane.showConfirmDialog(null, "Desea confirmar los cambios", "Modificar?", JOptionPane.YES_NO_OPTION);
          if (n == JOptionPane.YES_OPTION) {
              String texto=txaLetra.getText().replace("\n", "\r\n");
            String ruta="." + File.separator + "letras";
            ruta+= File.separator + convertByteToString(tem.getSong().getId())+".txt";
              System.out.println(ruta);
              try {
                  RandomAccessFile archivo = new RandomAccessFile(ruta, "rw");
                  archivo.writeUTF(texto);
                  archivo.close();
                  tem.getSong().setLetra(ruta);
                 Archivo file = new Archivo();
                 file.modificiar(Temporal.getSong());
                 JOptionPane.showMessageDialog(null, "CANCION MODIFICADA");
                this.setVisible(false);
              } catch (FileNotFoundException ex) {
                  Logger.getLogger(Letra.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IOException ex) {
                  Logger.getLogger(Letra.class.getName()).log(Level.SEVERE, null, ex);
              }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Letra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Letra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Letra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Letra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Letra().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Letra.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rModificar;
    private javax.swing.JTextArea txaLetra;
    // End of variables declaration//GEN-END:variables
}
